### Read all user
GET http://localhost:3000/api/v1/users

### Create user
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
    "username": "ju",
    "email":" susanfsf@example.com",
    "password": "12352sfsd12649565"
}


# ### Update user
# PUT http://localhost:3000/api/v1/users/1
# Content-Type: application/json

# {
#     "username": "Word",
#     "email":" susan@example.com",
#     "password": "1234"
# }

 ### Delete user in mockupData
DELETE http://localhost:3000/api/v1/users/4