@baseUrl = http://localhost:3000/api/v2/user
@validEmail    =aliba@xmail.com
@validPassword =aliba25806

###
POST {{baseUrl}}/login
Content-Type: application/json

{
    "email": "{{validEmail}}",
    "password": "{{validPassword}}"
}

###
POST {{baseUrl}}/login
Content-Type: application/json

{
    "email": "{{validEmail}}"
}

### password wrong
POST {{baseUrl}}/login
Content-Type: application/json

{
    "email": "{{validEmail}}",
    "password": "wrongpassword"
}

### not found
POST {{baseUrl}}/login
Content-Type: application/json

{
    "email": "doesnotexist@example.com",
    "password": "password123"
}

### The REST Client stores the Set-Cookie header from request #1 automatically.
GET {{baseUrl}}/auth/me

###
GET {{baseUrl}}/auth/me
Cookie: accessToken=


### invalid
GET {{baseUrl}}/auth/me
Cookie: accessToken=this.is.not.a.valid.jwt

### logout
POST {{baseUrl}}/auth/logout

### no token af logout
GET {{baseUrl}}/auth/me