### Read all user
GET http://localhost:3000/api/v2/user

### Create user
POST http://localhost:3000/api/v2/user
Content-Type: application/json

{
    "username": "sanddy",
    "email":" asdff@",
    "password": "2ghj8llda",
    "role":"admin"
  
}

### Create user with hash
POST http://localhost:3000/api/v2/user/register
Content-Type: application/json

{
    "username": "aliba",
    "email":"aliba@xmail.com",
    "password": "aliba25806",
    "role":"user"

}

### login
POST http://localhost:3000/api/v2/user/login
Content-Type: application/json

{
    "email":"aliba@xmail.com",
    "password": "aliba25806"
}


# ### Update user
# PUT http://localhost:3000/api/v2/user
# Content-Type: application/json

# {
#     "username": "Word",
#     "email":" susan@example.com",
#     "password": "1234"
# }

### Delete user
# DELETE http://localhost:3000/api/v2/user/
# Content-Type: application/json

# {
#     "username": "null",
#     "email":"null",
#     "password": "null",
#     "role": "null"
# }