### Read all user
GET http://localhost:3000/api/v2/user

### Create user
POST http://localhost:3000/api/v2/user
Content-Type: application/json

{
    "username": "sanddy",
    "email":" dream@example.com",
    "password": "2ghj8llda",
    "role":"admin"
  
}

# ### Update user
# PUT http://localhost:3000/api/v2/user
# Content-Type: application/json

# {
#     "username": "Word",
#     "email":" susan@example.com",
#     "password": "1234"
# }

### Delete user
# DELETE http://localhost:3000/api/v2/user/
# Content-Type: application/json

# {
#     "username": "null",
#     "email":"null",
#     "password": "null",
#     "role": "null"
# }